In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
dataset = pd.read_csv('parkinsons_new.csv')


In [ ]:
dataset.head()

name  age sex  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  \
0  phon_R01_S01_1   50   M      119.992       157.302        74.997   
1  phon_R01_S01_2   52   F      122.400       148.650       113.819   
2  phon_R01_S01_3   54   M      116.682       131.111       111.555   
3  phon_R01_S01_4   57   F      116.676       137.871       111.366   
4  phon_R01_S01_5   59   M      116.014       141.781       110.655   

   MDVP:Jitter(%)  MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  \
0         0.00784           0.00007   0.00370   0.00554     0.01109   
1         0.00968           0.00008   0.00465   0.00696     0.01394   
2         0.01050           0.00009   0.00544   0.00781     0.01633   
3         0.00997           0.00009   0.00502   0.00698     0.01505   
4         0.01284           0.00011   0.00655   0.00908     0.01966   

   MDVP:Shimmer  MDVP:Shimmer(dB)  Shimmer:APQ3  Shimmer:APQ5  MDVP:APQ  \
0       0.04374             0.426       0.02182       0.03130   0.02971   
1       0.06134             0.626       0.03134       0.04518   0.04368   
2       0.05233             0.482       0.02757       0.03858   0.03590   
3       0.05492             0.517       0.02924       0.04005   0.03772   
4       0.06425             0.584       0.03490       0.04825   0.04465   

   Shimmer:DDA      NHR     HNR  status  
0      0.06545  0.02211  21.033       1  
1      0.09403  0.01929  19.085       1  
2      0.08270  0.01309  20.651       1  
3      0.08771  0.01353  20.644       1  
4      0.10470  0.01767  19.649       1

In [ ]:
dataset.tail()

name  age sex  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  \
190  phon_R01_S50_2   74   F      174.188       230.978        94.261   
191  phon_R01_S50_3   52   F      209.516       253.017        89.488   
192  phon_R01_S50_4   62   F      174.688       240.005        74.287   
193  phon_R01_S50_5   78   F      198.764       396.961        74.904   
194  phon_R01_S50_6   69   F      214.289       260.277        77.973   

     MDVP:Jitter(%)  MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  \
190         0.00459           0.00003   0.00263   0.00259     0.00790   
191         0.00564           0.00003   0.00331   0.00292     0.00994   
192         0.01360           0.00008   0.00624   0.00564     0.01873   
193         0.00740           0.00004   0.00370   0.00390     0.01109   
194         0.00567           0.00003   0.00295   0.00317     0.00885   

     MDVP:Shimmer  MDVP:Shimmer(dB)  Shimmer:APQ3  Shimmer:APQ5  MDVP:APQ  \
190       0.04087             0.405       0.02336       0.02498   0.02745   
191       0.02751             0.263       0.01604       0.01657   0.01879   
192       0.02308             0.256       0.01268       0.01365   0.01667   
193       0.02296             0.241       0.01265       0.01321   0.01588   
194       0.01884             0.190       0.01026       0.01161   0.01373   

     Shimmer:DDA      NHR     HNR  status  
190      0.07008  0.02764  19.517       0  
191      0.04812  0.01810  19.147       0  
192      0.03804  0.10715  17.883       0  
193      0.03794  0.07223  19.020       0  
194      0.03078  0.04398  21.209       0

In [ ]:
dataset.shape

(195, 20)

In [ ]:
dataset.columns

Index(['name', 'age', 'sex', 'MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)',
       'MDVP:Jitter(%)', 'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ',
       'Jitter:DDP', 'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3',
       'Shimmer:APQ5', 'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'status'],
      dtype='object')

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   age               195 non-null    int64  
 2   sex               195 non-null    object 
 3   MDVP:Fo(Hz)       195 non-null    float64
 4   MDVP:Fhi(Hz)      195 non-null    float64
 5   MDVP:Flo(Hz)      195 non-null    float64
 6   MDVP:Jitter(%)    195 non-null    float64
 7   MDVP:Jitter(Abs)  195 non-null    float64
 8   MDVP:RAP          195 non-null    float64
 9   MDVP:PPQ          195 non-null    float64
 10  Jitter:DDP        195 non-null    float64
 11  MDVP:Shimmer      195 non-null    float64
 12  MDVP:Shimmer(dB)  195 non-null    float64
 13  Shimmer:APQ3      195 non-null    float64
 14  Shimmer:APQ5      195 non-null    float64
 15  MDVP:APQ          195 non-null    float64
 16  Shimmer:DDA       195 non-null    float64
 1

In [ ]:
dataset.describe()

age  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
count  195.000000   195.000000    195.000000    195.000000      195.000000   
mean    64.374359   154.228641    197.104918    116.324631        0.006220   
std      9.095051    41.390065     91.491548     43.521413        0.004848   
min     50.000000    88.333000    102.145000     65.476000        0.001680   
25%     57.000000   117.572000    134.862500     84.291000        0.003460   
50%     63.000000   148.790000    175.829000    104.315000        0.004940   
75%     72.000000   182.769000    224.205500    140.018500        0.007365   
max     79.000000   260.105000    592.030000    239.170000        0.033160   

       MDVP:Jitter(Abs)    MDVP:RAP    MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
count        195.000000  195.000000  195.000000  195.000000    195.000000   
mean           0.000044    0.003306    0.003446    0.009920      0.029709   
std            0.000035    0.002968    0.002759    0.008903      0.018857   
min            0.000007    0.000680    0.000920    0.002040      0.009540   
25%            0.000020    0.001660    0.001860    0.004985      0.016505   
50%            0.000030    0.002500    0.002690    0.007490      0.022970   
75%            0.000060    0.003835    0.003955    0.011505      0.037885   
max            0.000260    0.021440    0.019580    0.064330      0.119080   

       MDVP:Shimmer(dB)  Shimmer:APQ3  Shimmer:APQ5    MDVP:APQ  Shimmer:DDA  \
count        195.000000    195.000000    195.000000  195.000000   195.000000   
mean           0.282251      0.015664      0.017878    0.024081     0.046993   
std            0.194877      0.010153      0.012024    0.016947     0.030459   
min            0.085000      0.004550      0.005700    0.007190     0.013640   
25%            0.148500      0.008245      0.009580    0.013080     0.024735   
50%            0.221000      0.012790      0.013470    0.018260     0.038360   
75%            0.350000      0.020265      0.022380    0.029400     0.060795   
max            1.302000      0.056470      0.079400    0.137780     0.169420   

              NHR         HNR      status  
count  195.000000  195.000000  195.000000  
mean     0.024847   21.885974    0.753846  
std      0.040418    4.425764    0.431878  
min      0.000650    8.441000    0.000000  
25%      0.005925   19.198000    1.000000  
50%      0.011660   22.085000    1.000000  
75%      0.025640   25.075500    1.000000  
max      0.314820   33.047000    1.000000

In [ ]:
pd.isnull(dataset).sum()

name                0
age                 0
sex                 0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
dtype: int64

In [ ]:
#droping a particular column, axis =1
dataset = dataset.drop(['name'], axis=1)

In [ ]:
dataset = pd.get_dummies(dataset, prefix_sep='sex')

In [ ]:
dataset.head()

age  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0   50      119.992       157.302        74.997         0.00784   
1   52      122.400       148.650       113.819         0.00968   
2   54      116.682       131.111       111.555         0.01050   
3   57      116.676       137.871       111.366         0.00997   
4   59      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0           0.00007   0.00370   0.00554     0.01109       0.04374   
1           0.00008   0.00465   0.00696     0.01394       0.06134   
2           0.00009   0.00544   0.00781     0.01633       0.05233   
3           0.00009   0.00502   0.00698     0.01505       0.05492   
4           0.00011   0.00655   0.00908     0.01966       0.06425   

   MDVP:Shimmer(dB)  Shimmer:APQ3  Shimmer:APQ5  MDVP:APQ  Shimmer:DDA  \
0             0.426       0.02182       0.03130   0.02971      0.06545   
1             0.626       0.03134       0.04518   0.04368      0.09403   
2             0.482       0.02757       0.03858   0.03590      0.08270   
3             0.517       0.02924       0.04005   0.03772      0.08771   
4             0.584       0.03490       0.04825   0.04465      0.10470   

       NHR     HNR  status  sexsexF  sexsexM  
0  0.02211  21.033       1    False     True  
1  0.01929  19.085       1     True    False  
2  0.01309  20.651       1    False     True  
3  0.01353  20.644       1     True    False  
4  0.01767  19.649       1    False     True

In [ ]:
X = dataset.loc[:, dataset.columns !="status"]
y = dataset["status"]

In [ ]:
X.head()

age  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0   50      119.992       157.302        74.997         0.00784   
1   52      122.400       148.650       113.819         0.00968   
2   54      116.682       131.111       111.555         0.01050   
3   57      116.676       137.871       111.366         0.00997   
4   59      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0           0.00007   0.00370   0.00554     0.01109       0.04374   
1           0.00008   0.00465   0.00696     0.01394       0.06134   
2           0.00009   0.00544   0.00781     0.01633       0.05233   
3           0.00009   0.00502   0.00698     0.01505       0.05492   
4           0.00011   0.00655   0.00908     0.01966       0.06425   

   MDVP:Shimmer(dB)  Shimmer:APQ3  Shimmer:APQ5  MDVP:APQ  Shimmer:DDA  \
0             0.426       0.02182       0.03130   0.02971      0.06545   
1             0.626       0.03134       0.04518   0.04368      0.09403   
2             0.482       0.02757       0.03858   0.03590      0.08270   
3             0.517       0.02924       0.04005   0.03772      0.08771   
4             0.584       0.03490       0.04825   0.04465      0.10470   

       NHR     HNR  sexsexF  sexsexM  
0  0.02211  21.033    False     True  
1  0.01929  19.085     True    False  
2  0.01309  20.651    False     True  
3  0.01353  20.644     True    False  
4  0.01767  19.649    False     True

In [ ]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: status, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state =0)

In [ ]:
print ("Dimention for X train:", X_train.shape)
print ("Dimention for X test:", X_test.shape)
print ("Dimention for y train:", y_train.shape)
print ("Dimention for y test:", y_test.shape)

Dimention for X train: (156, 19)
Dimention for X test: (39, 19)
Dimention for y train: (156,)
Dimention for y test: (39,)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
X_train

array([[-1.10902309,  0.42106183,  0.05057195, ...,  0.92083391,
        -1.        ,  1.        ],
       [-0.67514823, -0.95694554, -0.73133513, ..., -0.65388412,
         1.        , -1.        ],
       [ 0.40953893,  1.21847901,  0.28739437, ..., -0.67914342,
        -1.        ,  1.        ],
       ...,
       [-0.24127336,  0.41390707,  2.52073344, ...,  0.87253104,
         1.        , -1.        ],
       [ 1.16881995,  2.46491405,  0.59348186, ...,  1.11958473,
         1.        , -1.        ],
       [ 0.73494508, -1.09278562, -0.91648442, ...,  1.06308366,
        -1.        ,  1.        ]])

In [ ]:
X_test

array([[-7.7350112 , -3.96978502, -2.09751106, ..., -5.84237572,
        -7.        ,  1.        ],
       [-7.72990646, -3.97065348, -2.09759257, ..., -5.91968574,
         1.        , -7.        ],
       [-7.71714462, -3.96928246, -2.09748637, ..., -5.92092583,
        -7.        ,  1.        ],
       ...,
       [-7.72480173, -3.96978953, -2.09725355, ..., -5.84474712,
         1.        , -7.        ],
       [-7.70821133, -3.96849692, -2.09745446, ..., -5.83261814,
         1.        , -7.        ],
       [-7.71331606, -3.9707391 , -2.09761187, ..., -5.83539204,
        -7.        ,  1.        ]])

In [ ]:
from sklearn import svm
cl = svm.SVC(kernel='linear', C=0.01)
cl.fit(X_train, y_train)

SVC(C=0.01, kernel='linear')

In [ ]:
y_pred = cl.predict(X_train)

In [ ]:
y_pred_1 = cl.predict(X_test)
y_pred_1

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0])